function [Ex Ey Ez] = calcForce(xyz, sigma, rcut, h, ExM, EyM, EzM)
    N = size(ExM,1);
    rcut2 = rcut^2;
    nk = ceil(rcut/h);
    Ex = zeros(size(xyz,1),1);
    Ey = zeros(size(xyz,1),1);
    Ez = zeros(size(xyz,1),1);
    for i=1:size(xyz,1)
        x = xyz(1,1);
        y = xyz(1,2);
        z = xyz(1,3);
        ix = round(x/h-0.5);
        iy = round(y/h-0.5);
        iz = round(z/h-0.5);
        for lz=iz-nk:iz+nk
            for ly=iy-nk:iy+nk
                for lx=ix-nk:ix+nk
                    r2 = ((lx+0.5)*h-x)^2 + ((ly+0.5)*h-y)^2 + ((lz+0.5)*h-z)^2;
                    if (r2 < rcut2)
                        fac = exp(-r2/(2*sigma*sigma));
                        mx = mod(lx-1+N,N);
                        my = mod(ly-1+N,N);
                        mz = mod(lz-1+N,N);

                        nx = mod(lx+N,N);
                        ny = mod(ly+N,N);
                        nz = mod(lz+N,N);
                        
                        px = mod(lx+1+N,N);
                        py = mod(ly+1+N,N);
                        pz = mod(lz+1+N,N);

                        p2x = mod(lx+2+N,N);
                        p2y = mod(ly+2+N,N);
                        p2z = mod(lz+2+N,N);

                        Ex0 = ExM(nx+1,ny+1,nz+1);
                        Ey0 = EyM(nx+1,ny+1,nz+1);
                        Ez0 = EzM(nx+1,ny+1,nz+1);
                        
                        dEx_dx = 5/6*(ExM(px+1,ny+1,nz+1) - ...
                                      ExM(nx+1,ny+1,nz+1))/h + ...
                                 1/12*(ExM(nx+1,ny+1,nz+1) - ...
                                       ExM(mx+1,ny+1,nz+1))/h + ...
                                 1/12*(ExM(p2x+1,ny+1,nz+1) - ...
                                       ExM(px+1,ny+1,nz+1))/h;                        

                        dEy_dx = 5/6*(EyM(px+1,ny+1,nz+1) - ...
                                      EyM(nx+1,ny+1,nz+1))/h + ...
                                 1/12*(EyM(nx+1,ny+1,nz+1) - ...
                                       EyM(mx+1,ny+1,nz+1))/h + ...
                                 1/12*(EyM(p2x+1,ny+1,nz+1) - ...
                                       EyM(px+1,ny+1,nz+1))/h;                        

                        dEz_dx = 5/6*(EzM(px+1,ny+1,nz+1) - ...
                                      EzM(nx+1,ny+1,nz+1))/h + ...
                                 1/12*(EzM(nx+1,ny+1,nz+1) - ...
                                       EzM(mx+1,ny+1,nz+1))/h + ...
                                 1/12*(EzM(p2x+1,ny+1,nz+1) - ...
                                       EzM(px+1,ny+1,nz+1))/h;                        
                        
                        dEx_dy = 5/6*(ExM(nx+1,py+1,nz+1) - ...
                                      ExM(nx+1,ny+1,nz+1))/h + ...
                                 1/12*(ExM(nx+1,ny+1,nz+1) - ...
                                       ExM(nx+1,my+1,nz+1))/h + ...
                                 1/12*(ExM(nx+1,p2y+1,nz+1) - ...
                                       ExM(nx+1,py+1,nz+1))/h;                        

                        dEy_dy = 5/6*(EyM(nx+1,py+1,nz+1) - ...
                                      EyM(nx+1,ny+1,nz+1))/h + ...
                                 1/12*(EyM(nx+1,ny+1,nz+1) - ...
                                       EyM(nx+1,my+1,nz+1))/h + ...
                                 1/12*(EyM(nx+1,p2y+1,nz+1) - ...
                                       EyM(nx+1,py+1,nz+1))/h;                        

                        dEz_dy = 5/6*(EzM(nx+1,py+1,nz+1) - ...
                                      EzM(nx+1,ny+1,nz+1))/h + ...
                                 1/12*(EzM(nx+1,ny+1,nz+1) - ...
                                       EzM(nx+1,my+1,nz+1))/h + ...
                                 1/12*(EzM(nx+1,p2y+1,nz+1) - ...
                                       EzM(nx+1,py+1,nz+1))/h;                        

                        Ex(i) = Ex(i) + 2*(Ex0*dEx_dx + Ey0*dEy_dx + Ez0*dEz_dx)*fac;
                        Ey(i) = Ey(i) + 2*(Ex0*dEx_dy + Ey0*dEy_dy + Ez0*dEz_dy)*fac;
                        %Ey(i) = Ey(i) + EyM(nx+1,ny+1,nz+1)*fac;
                        %Ez(i) = Ez(i) + EzM(nx+1,ny+1,nz+1)*fac;
                    end
                end
            end
        end
        Ex(i) = Ex(i)*(2*pi*sigma*sigma)^(-3/2)*h*h*h;
        Ey(i) = Ey(i)*(2*pi*sigma*sigma)^(-3/2)*h*h*h;
        Ez(i) = Ez(i)*(2*pi*sigma*sigma)^(-3/2)*h*h*h;
    end
end
